##### MkDocs configuration #####

# Meta
site_name: 'WildBeast Documentation'
site_description: 'Welcome to the WB documentation'
site_author: 'TheSharks'
site_url: 'https://docs.thesharks.xyz'
site_favicon: 'img/favicon.ico'

# Sitemap
pages:
  - Home: 'index.md'
  - Commands:
    - Command reference: 'commands.md'
    - Custom commands: 'custom_commands.md'
  - Installation:
    - Linux installation: 'install_linux.md'
    - Windows installation: 'install_windows.md'
    - Docker installation: 'install_docker.md'
  - Selfhosters:
    - Updating: 'updating.md'
    - Sharding: 'sharding.md'
    - PowerShell to CMD: 'powershell.md'
  - Credits: 'credits.md'

# Theme
theme: 'material'

##### Material configuration #####

# Repo
repo_name: 'TheSharks/WildBeastDocs'
repo_url: 'https://github.com/TheSharks/WildBeastDocs'

# Copyright
copyright: 'Copyright © 2016-2017 TheSharks, "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'

# Additional options
extra:
  feature:
    tabs: true
  logo: 'img/wb-head-circle.png'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Droid Sans'
    font: 'Droid Sans Mono'
  social:
    - type: 'github'
      link: 'https://github.com/TheSharks'

# Markdown extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.critic
  - pymdownx.inlinehilite
